# CircleCI configuration file
version: 2.1

jobs:
  build:
    docker:
    # Primary container image where all steps run
     - image: quay.io/hemanth22/rockylinux9:9
    steps:
      - checkout
      - run:
          name: Execute Shell script
          command: |
            dnf install procps-ng -y
            chmod 755 ./redhat-reportv2.sh
            ./redhat-reportv2.sh
      - run:
          name: Archive the artifacts
          command: |
            cp -v redhat-report.html /tmp/

      - store_artifacts:
         path: /tmp/redhat-report.html

workflows:
  build_and_test:
    jobs:
      - build